ibexa:
    siteaccess:
        default_siteaccess: eng
        list:
            - eng
            - admin
            - ngadminui
            - legacy_admin
        groups:
            frontend_group:
                - eng
            ngadmin_group:
                - ngadminui
                - legacy_admin
            admin_group:
                - admin
    system:
        frontend_group:
            translation_siteaccesses:
                - eng
            content:
                tree_root:
                    location_id: '%ngsite.default.locations.tree_root.id%'
        eng:
            design: app
            languages:
                - eng-GB
            session:
                name: eZSESSID
        ngadminui:
            design: ngadminui
            languages:
                - eng-GB
            session:
                name: eZSESSID
        admin_group:
            languages:
                - eng-GB
            session:
                name: eZSESSID
        legacy_admin:
            languages:
                - eng-GB
netgen_layouts:
    design_list:
        app:
            - app
    system:
        frontend_group:
            design: app
ibexa_design_engine:
    design_list:
        app:
            - app
            - common
            - standard
        admin:
            - admin
            - standard
            - common
        ngadminui:
            - ngadminui
            - common
ez_publish_legacy:
    system:
        legacy_admin:
            legacy_mode: true
